apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/reminders/
  - ./dev-reminders-configmap.yaml
patches:
  - path: ./dev-reminders-patch-deploy.yaml
  - path: ./dev-reminders-patch-service.yaml
images:
  - name: reminders-image
    newName: localhost/charlieroth/reminders
    newTag: 0.0.1
