
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- EXTENSIONS 

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- TABLES 

CREATE TABLE lists (
 name character varying (255) NOT NULL,
 updated_at timestamp with time zone  NOT NULL,
 created_at timestamp with time zone  NOT NULL,
 id uuid  NOT NULL
);

CREATE TABLE lists_tasks (
 task_id uuid  NOT NULL,
 list_id uuid  NOT NULL
);

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

CREATE TABLE tasks (
 updated_at timestamp with time zone  NOT NULL,
 created_at timestamp with time zone  NOT NULL,
 id uuid  NOT NULL,
 title text  NOT NULL,
 completed boolean  NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE lists ADD CONSTRAINT lists_pkey PRIMARY KEY (id);

ALTER TABLE lists_tasks ADD CONSTRAINT lists_tasks_list_id_fkey FOREIGN KEY (list_id) REFERENCES lists(id);

ALTER TABLE lists_tasks ADD CONSTRAINT lists_tasks_pkey PRIMARY KEY (list_id);

ALTER TABLE lists_tasks ADD CONSTRAINT lists_tasks_pkey PRIMARY KEY (task_id);

ALTER TABLE lists_tasks ADD CONSTRAINT lists_tasks_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id);

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

ALTER TABLE tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX lists_pkey ON public.lists USING btree (id)

CREATE UNIQUE INDEX lists_tasks_pkey ON public.lists_tasks USING btree (list_id, task_id)

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id)

