
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- EXTENSIONS 

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- TABLES 

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

CREATE TABLE tasks (
 title text  NOT NULL,
 id uuid  NOT NULL,
 created_at timestamp with time zone  NOT NULL,
 updated_at timestamp with time zone  NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

ALTER TABLE tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id)

