services:
  database:
    image: postgres:16.4
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/pg_hba.conf
    command: ["-c", "hba_file=/etc/pg_hba.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpu_count: 2
    networks:
      reminders-system-network:
        ipv4_address: 10.5.0.2

  init-migrate-seed:
    image: localhost/charlieroth/reminders:0.0.1
    pull_policy: never
    container_name: init-migrate-seed
    restart: unless-stopped
    entrypoint: ["./admin", "migrate-seed"]
    environment:
      - REMINDERS_DB_USER=postgres
      - REMINDERS_DB_PASSWORD=postgres
      - REMINDERS_DB_HOST=database
      - REMINDERS_DISABLE_TLS=true
    networks:
      reminders-system-network:
        ipv4_address: 10.5.0.10
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - database

  reminders:
    image: localhost/charlieroth/reminders:0.0.1
    pull_policy: never
    container_name: reminders
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GOMAXPROCS=2
      - REMINDERS_DB_USER=postgres
      - REMINDERS_DB_PASSWORD=postgres
      - REMINDERS_DB_HOST=database
      - REMINDERS_DISABLE_TLS=true
      - KUBERNETES_NAMESPACE=compose
      - KUBERNETES_NAME=reminders-system
      - KUBERNETES_POD_IP=10.5.0.5
      - KUBERNETES_NODE_NAME=reminders
    expose:
      - "8080:8080"
    networks:
      reminders-system-network:
        ipv4_address: 10.5.0.5
    depends_on:
      - database

volumes:
  database: {}

networks:
  reminders-system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
